services:
  - type: web
    name: our-places-game
    runtime: static
    buildCommand: cd rishon3d && npm install && npm run build
    staticPublishPath: ./rishon3d/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
