import { InteriorLayout, buildWallGrid } from '../../data/interiorLayouts';

export const AIRPORT_INTERIOR_LAYOUT: InteriorLayout = {
  id: 'airport-interior',
  widthInTiles: 36,
  heightInTiles: 20,
  wallGrid: buildWallGrid(36, 20, [{ x: 0, y: 0, w: 36, h: 20 }], []),
  floors: [
    { tileX: 1, tileY: 14, width: 34, height: 4, floorType: 'tile_floor' },
    { tileX: 1, tileY: 12, width: 34, height: 2, floorType: 'carpet_beige' },
    { tileX: 1, tileY: 8, width: 34, height: 4, floorType: 'tile_floor' },
    { tileX: 1, tileY: 6, width: 34, height: 2, floorType: 'carpet_beige' },
    { tileX: 12, tileY: 2, width: 23, height: 4, floorType: 'carpet' },
    { tileX: 1, tileY: 2, width: 11, height: 4, floorType: 'wood' },
  ],
  decorations: [
    // CHECK-IN (y=14-17)
    { type: 'airport-counter', tileX: 8, tileY: 15 },
    { type: 'airport-counter', tileX: 14, tileY: 15 },
    { type: 'airport-counter', tileX: 20, tileY: 15 },
    { type: 'airport-counter', tileX: 26, tileY: 15 },
    { type: 'airport-rope-barrier', tileX: 7, tileY: 14 },
    { type: 'airport-rope-barrier', tileX: 13, tileY: 14 },
    { type: 'airport-rope-barrier', tileX: 19, tileY: 14 },
    { type: 'airport-rope-barrier', tileX: 25, tileY: 14 },
    { type: 'airport-luggage-cart', tileX: 10, tileY: 17 },
    { type: 'airport-luggage-cart', tileX: 22, tileY: 17 },
    { type: 'airport-plant', tileX: 4, tileY: 14 },
    { type: 'airport-plant', tileX: 32, tileY: 14 },
    { type: 'airport-bench', tileX: 4, tileY: 16 },
    { type: 'airport-bench', tileX: 32, tileY: 16 },
    { type: 'airport-luggage-belt', tileX: 14, tileY: 16 },
    // PASSPORT CONTROL (y=12-13 corridor)
    { type: 'airport-passport-desk', tileX: 18, tileY: 12 },
    // SECURITY (y=8-11)
    { type: 'airport-metal-detector', tileX: 12, tileY: 10 },
    { type: 'airport-metal-detector', tileX: 24, tileY: 10 },
    { type: 'airport-conveyor-belt', tileX: 14, tileY: 9 },
    { type: 'airport-conveyor-belt', tileX: 26, tileY: 9 },
    { type: 'airport-rope-barrier', tileX: 10, tileY: 11 },
    { type: 'airport-rope-barrier', tileX: 16, tileY: 11 },
    { type: 'airport-rope-barrier', tileX: 22, tileY: 11 },
    { type: 'airport-rope-barrier', tileX: 28, tileY: 11 },
    { type: 'airport-bin', tileX: 8, tileY: 10 },
    { type: 'airport-bin', tileX: 30, tileY: 10 },
    // GATE/BOARDING (y=2-5, x=12-35)
    { type: 'airport-gate-desk', tileX: 24, tileY: 3 },
    { type: 'airport-departures-board', tileX: 16, tileY: 2 },
    { type: 'airport-bench', tileX: 14, tileY: 3 },
    { type: 'airport-bench', tileX: 14, tileY: 5 },
    { type: 'airport-bench', tileX: 20, tileY: 3 },
    { type: 'airport-bench', tileX: 20, tileY: 5 },
    { type: 'airport-bench', tileX: 28, tileY: 5 },
    { type: 'airport-window', tileX: 13, tileY: 2 },
    { type: 'airport-window', tileX: 21, tileY: 2 },
    { type: 'airport-window', tileX: 29, tileY: 2 },
    { type: 'airport-window', tileX: 33, tileY: 2 },
    { type: 'airport-plant', tileX: 12, tileY: 2 },
    { type: 'airport-plant', tileX: 34, tileY: 2 },
    // CAFE (y=2-5, x=1-11)
    { type: 'airport-cafe-counter', tileX: 3, tileY: 3 },
    { type: 'airport-stool', tileX: 6, tileY: 3 },
    { type: 'airport-stool', tileX: 6, tileY: 5 },
    { type: 'airport-stool', tileX: 9, tileY: 3 },
    { type: 'airport-stool', tileX: 9, tileY: 5 },
    { type: 'airport-cafe-menu', tileX: 2, tileY: 3 },
    { type: 'airport-plant', tileX: 1, tileY: 2 },
    { type: 'airport-plant', tileX: 11, tileY: 2 },
  ],
  entrance: { tileX: 18, tileY: 18 },
  exit: { tileX: 17, tileY: 18, width: 3, height: 2, promptText: 'Exit Airport' },
  exitDoorStyle: 'glass',
  cameraZoom: 2.0,
};
