import { InteriorLayout } from '../../data/interiorLayouts';
import { buildWallGrid } from '../../data/interiorLayouts';

export const AIRPORT_ENTRANCE_LAYOUT: InteriorLayout = {
  id: 'airport-entrance',
  widthInTiles: 20,
  heightInTiles: 14,
  wallGrid: buildWallGrid(20, 14, [{ x: 0, y: 0, w: 20, h: 14 }], []),
  floors: [
    { tileX: 1, tileY: 1, width: 18, height: 12, floorType: 'tile_floor' },
    { tileX: 5, tileY: 6, width: 10, height: 5, floorType: 'carpet_beige' },
  ],
  decorations: [
    { tileX: 4, tileY: 2, type: 'airport-counter' },
    { tileX: 7, tileY: 2, type: 'airport-counter' },
    { tileX: 10, tileY: 2, type: 'airport-counter' },
    { tileX: 13, tileY: 2, type: 'airport-counter' },
    { tileX: 9, tileY: 1, type: 'airport-departures-board' },
    { tileX: 6, tileY: 7, type: 'airport-bench' },
    { tileX: 12, tileY: 7, type: 'airport-bench' },
    { tileX: 6, tileY: 9, type: 'airport-bench' },
    { tileX: 12, tileY: 9, type: 'airport-bench' },
    { tileX: 17, tileY: 2, type: 'sign-departures' },
    { tileX: 1, tileY: 5, type: 'airport-plant' },
    { tileX: 18, tileY: 5, type: 'airport-plant' },
    { tileX: 2, tileY: 11, type: 'airport-luggage-cart' },
  ],
  entrance: { tileX: 10, tileY: 12 },
  exit: {
    tileX: 9,
    tileY: 12,
    width: 3,
    height: 2,
    promptText: 'Tap to go out',
  },
  forwardExit: {
    tileX: 17,
    tileY: 2,
    width: 2,
    height: 2,
    promptText: 'Tap to proceed',
  },
  nextScene: 'AirportSecurityScene',
  cameraZoom: 2.0,
};

export const AIRPORT_SECURITY_LAYOUT: InteriorLayout = {
  id: 'airport-security',
  widthInTiles: 12,
  heightInTiles: 8,
  wallGrid: buildWallGrid(12, 8, [{ x: 0, y: 0, w: 12, h: 8 }], []),
  floors: [
    { tileX: 1, tileY: 1, width: 10, height: 6, floorType: 'tile_floor' },
  ],
  decorations: [
    { tileX: 4, tileY: 3, type: 'airport-conveyor-belt' },
    { tileX: 6, tileY: 3, type: 'airport-conveyor-belt' },
    { tileX: 7, tileY: 5, type: 'airport-metal-detector' },
    { tileX: 3, tileY: 2, type: 'airport-rope-barrier' },
    { tileX: 3, tileY: 4, type: 'airport-rope-barrier' },
    { tileX: 9, tileY: 1, type: 'sign-gate' },
    { tileX: 3, tileY: 3, type: 'airport-bin' },
    { tileX: 8, tileY: 3, type: 'airport-bin' },
  ],
  entrance: { tileX: 2, tileY: 4 },
  exit: {
    tileX: 1,
    tileY: 4,
    width: 2,
    height: 2,
    promptText: 'Tap to go back',
  },
  forwardExit: {
    tileX: 9,
    tileY: 4,
    width: 2,
    height: 2,
    promptText: 'Tap to proceed',
  },
  nextScene: 'AirportGateScene',
  previousScene: 'AirportEntranceScene',
  cameraZoom: 2.0,
};

export const AIRPORT_GATE_LAYOUT: InteriorLayout = {
  id: 'airport-gate',
  widthInTiles: 22,
  heightInTiles: 14,
  wallGrid: buildWallGrid(22, 14, [{ x: 0, y: 0, w: 22, h: 14 }], []),
  floors: [
    { tileX: 1, tileY: 1, width: 9, height: 12, floorType: 'wood' },
    { tileX: 10, tileY: 1, width: 11, height: 12, floorType: 'tile_floor' },
  ],
  decorations: [
    { tileX: 3, tileY: 2, type: 'airport-cafe-counter' },
    { tileX: 5, tileY: 2, type: 'airport-cafe-counter' },
    { tileX: 7, tileY: 2, type: 'airport-cafe-counter' },
    { tileX: 4, tileY: 4, type: 'airport-stool' },
    { tileX: 6, tileY: 4, type: 'airport-stool' },
    { tileX: 5, tileY: 1, type: 'airport-cafe-menu' },
    { tileX: 2, tileY: 1, type: 'sign-cafe' },
    { tileX: 12, tileY: 6, type: 'airport-bench' },
    { tileX: 17, tileY: 6, type: 'airport-bench' },
    { tileX: 12, tileY: 9, type: 'airport-bench' },
    { tileX: 17, tileY: 9, type: 'airport-bench' },
    { tileX: 12, tileY: 1, type: 'airport-window' },
    { tileX: 15, tileY: 1, type: 'airport-window' },
    { tileX: 18, tileY: 1, type: 'airport-window' },
    { tileX: 19, tileY: 2, type: 'airport-gate-desk' },
    { tileX: 19, tileY: 1, type: 'sign-gate-number' },
  ],
  entrance: { tileX: 1, tileY: 7 },
  exit: {
    tileX: 1,
    tileY: 6,
    width: 1,
    height: 3,
    promptText: 'Tap to go back',
  },
  previousScene: 'AirportSecurityScene',
  cameraZoom: 1.8,
};
